services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb?sslmode=disable
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - TOKEN=${TELEGRAM_BOT_TOKEN}
      - SERVER_IP=${SERVER_IP}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - db
    ports:
      - "8444:8443"
    networks:
      - app-network
    volumes:
      - ./certs:/root/certs

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - app
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge

